name: Deploy to EC2

on:
  push:
    branches:
      - main  # Replace with your target branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        echo "Running deployment script"
        # Add your deployment commands here, e.g., using SSH to run scripts on EC2
